package com.continuedev.eclipse.continue.constants;

import java.util.Set;

/**
 * Mirrors the message routing tables defined in core/protocol/passThrough.ts so
 * the Eclipse bridge knows whether a payload should be handled locally or sent
 * to the Continue core process.
 */
public final class MessageTypes {

    private MessageTypes() {}

    public static final Set<String> IDE_MESSAGE_TYPES =
        Set.of(
            "readRangeInFile",
            "isTelemetryEnabled",
            "getUniqueId",
            "getDiff",
            "getTerminalContents",
            "getWorkspaceDirs",
            "showLines",
            "writeFile",
            "fileExists",
            "showVirtualFile",
            "openFile",
            "runCommand",
            "saveFile",
            "readFile",
            "showDiff",
            "getOpenFiles",
            "getCurrentFile",
            "getPinnedFiles",
            "getSearchResults",
            "getFileResults",
            "getProblems",
            "subprocess",
            "getBranch",
            "getTags",
            "getIdeInfo",
            "getIdeSettings",
            "getRepoName",
            "listDir",
            "getGitRootPath",
            "getFileStats",
            "insertAtCursor",
            "applyToFile",
            "getControlPlaneSessionInfo",
            "logoutOfControlPlane",
            "showToast",
            "openUrl",
            "isWorkspaceRemote",
            "toggleDevTools",
            "showTutorial",
            "copyText",
            "jetbrains/isOSREnabled",
            "jetbrains/getColors",
            "jetbrains/onLoad");

    public static final Set<String> PASS_THROUGH_TO_WEBVIEW =
        Set.of(
            "configUpdate",
            "indexProgress",
            "indexing/statusUpdate",
            "addContextItem",
            "refreshSubmenuItems",
            "isContinueInputFocused",
            "setTTSActive",
            "getWebviewHistoryLength",
            "getCurrentSessionId",
            "sessionUpdate",
            "didCloseFiles",
            "toolCallPartialOutput");

    public static final Set<String> PASS_THROUGH_TO_CORE =
        Set.of(
            "abort",
            "history/list",
            "history/delete",
            "history/load",
            "history/save",
            "history/clear",
            "devdata/log",
            "config/addModel",
            "config/newPromptFile",
            "config/newAssistantFile",
            "config/ideSettingsUpdate",
            "config/addLocalWorkspaceBlock",
            "config/getSerializedProfileInfo",
            "config/deleteModel",
            "config/refreshProfiles",
            "config/openProfile",
            "config/updateSharedConfig",
            "config/updateSelectedModel",
            "mcp/reloadServer",
            "mcp/startAuthentication",
            "mcp/removeAuthentication",
            "mcp/setServerEnabled",
            "mcp/getPrompt",
            "context/getContextItems",
            "context/getSymbolsForFiles",
            "context/loadSubmenuItems",
            "context/addDocs",
            "context/removeDocs",
            "context/indexDocs",
            "autocomplete/complete",
            "autocomplete/cancel",
            "autocomplete/accept",
            "nextEdit/predict",
            "nextEdit/reject",
            "nextEdit/accept",
            "nextEdit/startChain",
            "nextEdit/deleteChain",
            "nextEdit/isChainAlive",
            "nextEdit/queue/getProcessedCount",
            "nextEdit/queue/dequeueProcessed",
            "nextEdit/queue/processOne",
            "nextEdit/queue/clear",
            "nextEdit/queue/abort",
            "tts/kill",
            "llm/complete",
            "llm/streamChat",
            "llm/listModels",
            "llm/compileChat",
            "streamDiffLines",
            "getDiffLines",
            "chatDescriber/describe",
            "conversation/compact",
            "stats/getTokensPerDay",
            "stats/getTokensPerModel",
            "index/setPaused",
            "index/forceReIndex",
            "index/forceReIndexFiles",
            "index/indexingProgressBarInitialized",
            "indexing/reindex",
            "indexing/abort",
            "indexing/setPaused",
            "docs/initStatuses",
            "docs/getDetails",
            "docs/getIndexedPages",
            "onboarding/complete",
            "addAutocompleteModel",
            "didChangeSelectedProfile",
            "didChangeSelectedOrg",
            "tools/call",
            "tools/evaluatePolicy",
            "tools/preprocessArgs",
            "controlPlane/openUrl",
            "isItemTooBig",
            "process/markAsBackgrounded",
            "process/isBackgrounded",
            "process/killTerminalProcess");
}
